server {
    listen 80;
    server_name tools.localhost;

    location / {
        root /usr/share/nginx/html;
        # This forces Nginx to serve tools.html even if you just go to /
        index tools.html;
        try_files /tools.html =404;
    }
}


# pgAdmin
server {
    listen 80;
    server_name pgadmin.localhost;
    location / {
        set $upstream_pgadmin wallet_pgadmin;
        proxy_pass http://$upstream_pgadmin:80;
        
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
    }
}

# Debezium UI
server {
    listen 80;
    server_name debezium.localhost;
    location / {
        set $upstream_debezium wallet_debezium_ui;
        proxy_pass http://$upstream_debezium:8080; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Redpanda Console
server {
    listen 80;
    server_name redpanda.localhost;
    location / {
        set $upstream_redpanda wallet_redpanda_ui;
        proxy_pass http://$upstream_redpanda:8080;
        
        proxy_set_header Host $host;
    }
}

# Mongo Express
server {
    listen 80;
    server_name mongo.localhost;
    location / {
        set $upstream_mongo wallet_mongo_ui;
        proxy_pass http://$upstream_mongo:8081;
        
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }
}